fix wf

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -9,3 +9,11 @@ jobs:
     steps:
       - name: Say hello
         run: echo "Hello, World!"
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: echo "I will fail exit 9"
+      
+      - name: Say hello
+        run: echo "Hello, World!"
